# Generated by Django 5.0.6 on 2024-06-10 19:11

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('construction_management', '0007_alter_obra_fecha_final'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarea', models.CharField(choices=[('obra_negra', 'Obra Negra'), ('obra_gris', 'Obra Gris'), ('obra_blanca', 'Obra Blanca')], max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_estimada_fin', models.DateField(default=datetime.datetime(2024, 7, 10, 19, 11, 6, 783829, tzinfo=datetime.timezone.utc))),
                ('estado', models.CharField(choices=[('asignada', 'Asignada'), ('en_desarrollo', 'En desarrollo'), ('en_revision', 'En revisión'), ('aceptada', 'Aceptada')], default='asignada', max_length=20)),
                ('capataz_encargado', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'tipo_usuario': 'Capataz de obra'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='construction_management.obra')),
                ('personal_asignado', models.ManyToManyField(limit_choices_to={'is_active': True, 'tipo_usuario__in': ['Peón', 'Ayudante de albañil']}, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
