# Generated by Django 5.0.6 on 2024-06-10 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_estimada_fin',
            field=models.DateField(default=datetime.datetime(2024, 7, 10, 19, 44, 35, 128278, tzinfo=datetime.timezone.utc)),
        ),
    ]
