# Generated by Django 5.0.6 on 2024-06-11 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tareas', '0002_alter_tarea_fecha_estimada_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_estimada_fin',
            field=models.DateField(default=datetime.datetime(2024, 7, 11, 8, 17, 25, 110934, tzinfo=datetime.timezone.utc)),
        ),
    ]
