# Generated by Django 4.2.13 on 2024-06-14 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tareas', '0008_alter_tarea_fecha_estimada_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_estimada_fin',
            field=models.DateField(default=datetime.datetime(2024, 7, 14, 6, 33, 37, 632309, tzinfo=datetime.timezone.utc)),
        ),
    ]
