version: '3'

services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
  postgres:
      image: postgres:14-alpine
      ports:
        - "5432:5432"
      volumes:
        - ~/apps/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=S3cret
        - POSTGRES_USER=citizix_user
        - POSTGRES_DB=citizix_db
