# Generated by Django 5.0.3 on 2024-03-29 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('tipo_obra', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('en desarrollo', 'En desarrollo'), ('en revisión', 'En revisión'), ('culminada', 'Culminada')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('foto_perfil', models.BinaryField(null=True)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('tipo_usuario', models.CharField(choices=[('Gerente', 'Gerente'), ('Director de obra', 'Director de obra'), ('Capataz de obra', 'Capataz de obra'), ('Peón', 'Peón'), ('Ayudante de albañil', 'Ayudante de albañil')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True)),
                ('estado', models.CharField(choices=[('asignada', 'Asignada'), ('en desarrollo', 'En desarrollo'), ('en revisión', 'En revisión'), ('aceptada', 'Aceptada')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('id_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.obra')),
                ('id_capataz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ObraPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('Peon', 'Peón'), ('Ayudante de albañil', 'Ayudante de albañil')], max_length=20)),
                ('id_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.obra')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='obra',
            name='id_capataz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_asignadas', to='user_management.usuario'),
        ),
        migrations.AddField(
            model_name='obra',
            name='id_director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_dirigidas', to='user_management.usuario'),
        ),
    ]
