# Generated by Django 5.0.4 on 2024-05-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_usuario_numero_identificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='estado',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('en desarrollo', 'En desarrollo'), ('en revisión', 'En revisión'), ('culminada', 'Culminada')], default='nueva', max_length=20),
        ),
        migrations.AlterField(
            model_name='obra',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
