# Generated by Django 5.0.4 on 2024-05-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_usuario_numero_identificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrapersonal',
            name='id_obra',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='id_obra',
        ),
        migrations.RemoveField(
            model_name='obrapersonal',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='id_capataz',
        ),
        migrations.DeleteModel(
            name='Obra',
        ),
        migrations.DeleteModel(
            name='ObraPersonal',
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
