# Generated by Django 5.0.4 on 2024-05-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_obra_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
