# Generated by Django 5.0.4 on 2024-05-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_obra_activo_alter_tarea_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='activo',
        ),
        migrations.AlterField(
            model_name='obra',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='estado',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('en desarrollo', 'En desarrollo'), ('en revisión', 'En revisión'), ('culminada', 'Culminada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='obra',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
