# Generated by Django 5.0.4 on 2024-05-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_remove_obra_activo_alter_obra_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='obra',
            name='estado',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('en desarrollo', 'En desarrollo'), ('en revisión', 'En revisión'), ('culminada', 'Culminada')], default='nueva', max_length=20),
        ),
        migrations.AlterField(
            model_name='obra',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
