# Generated by Django 5.0.6 on 2024-05-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(default='')),
                ('ubicacion', models.CharField(max_length=100)),
                ('tipo_obra', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('en desarrollo', 'En desarrollo'), ('en revisión', 'En revisión'), ('culminada', 'Culminada')], default='nueva', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ObraPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('Peon', 'Peón'), ('Ayudante de albañil', 'Ayudante de albañil')], default='Peón', max_length=20)),
            ],
        ),
    ]
