# Generated by Django 5.0.4 on 2024-05-06 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0003_remove_obrapersonal_id_obra_remove_tarea_id_obra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(default='')),
                ('ubicacion', models.CharField(max_length=100)),
                ('tipo_obra', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('en desarrollo', 'En desarrollo'), ('en revisión', 'En revisión'), ('culminada', 'Culminada')], default='nueva', max_length=20)),
                ('id_capataz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_asignadas', to='user_management.usuario')),
                ('id_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_dirigidas', to='user_management.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ObraPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('Peon', 'Peón'), ('Ayudante de albañil', 'Ayudante de albañil')], max_length=20)),
                ('id_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction_management.obra')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.usuario')),
            ],
        ),
    ]
