# Generated by Django 5.0.6 on 2024-05-16 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('construction_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='id_capataz',
            field=models.ManyToManyField(limit_choices_to={'tipo_usuario': 'Capataz de obra'}, related_name='obras_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obra',
            name='id_director',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'Director de obra'}, on_delete=django.db.models.deletion.CASCADE, related_name='obras_dirigidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obrapersonal',
            name='id_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction_management.obra'),
        ),
        migrations.AddField(
            model_name='obrapersonal',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
