# Generated by Django 4.2.13 on 2024-06-01 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('construction_management', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrapersonal',
            name='tipo_usuario',
        ),
        migrations.AlterField(
            model_name='obra',
            name='id_capataz',
            field=models.ManyToManyField(limit_choices_to={'is_active': True, 'tipo_usuario': 'Capataz de obra'}, related_name='obras_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='obra',
            name='id_director',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'tipo_usuario': 'Director de obra'}, on_delete=django.db.models.deletion.CASCADE, related_name='obras_dirigidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='obra',
            name='tipo_obra',
            field=models.CharField(choices=[('escuela', 'Escuela'), ('colegio', 'Colegio'), ('conjunto residencial', 'Conjunto residencial'), ('torre de apartamentos', 'Torre de apartamentos'), ('vial', 'Vial'), ('edificio', 'Edificio'), ('tienda', 'Tienda'), ('casa', 'Casa'), ('hospital', 'Hospital'), ('fábrica', 'Fábrica'), ('otros', 'Otros')], default='edificio', max_length=25),
        ),
        migrations.AlterField(
            model_name='obrapersonal',
            name='id_usuario',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'tipo_usuario': 'Peón'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
