# Generated by Django 4.2.13 on 2024-06-01 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('construction_management', '0003_remove_obrapersonal_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='obrapersonal',
            name='id_usuario',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_active', True), ('tipo_usuario__in', ['Peón', 'Ayudante de albañil'])), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
