# Generated by Django 4.2.13 on 2024-06-01 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0004_obra_fecha_inicio_alter_obrapersonal_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='fecha_final',
            field=models.DateField(default=datetime.datetime(2024, 11, 28, 22, 19, 6, 604222, tzinfo=datetime.timezone.utc), verbose_name='Fecha final'),
        ),
    ]
