# Generated by Django 4.2.13 on 2024-06-08 03:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0006_remove_obrapersonal_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='fecha_final',
            field=models.DateField(default=datetime.datetime(2024, 12, 5, 3, 30, 40, 535270, tzinfo=datetime.timezone.utc), verbose_name='Fecha final'),
        ),
        migrations.AlterField(
            model_name='obrapersonal',
            name='id_obra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='construction_management.obra'),
        ),
    ]
