# Generated by Django 4.2.13 on 2024-06-08 03:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0007_alter_obra_fecha_final_alter_obrapersonal_id_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrapersonal',
            name='id',
        ),
        migrations.AlterField(
            model_name='obra',
            name='fecha_final',
            field=models.DateField(default=datetime.datetime(2024, 12, 5, 3, 39, 9, 402835, tzinfo=datetime.timezone.utc), verbose_name='Fecha final'),
        ),
        migrations.AlterField(
            model_name='obrapersonal',
            name='id_obra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='construction_management.obra'),
        ),
    ]
