# Generated by Django 4.2.13 on 2024-06-08 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0008_remove_obrapersonal_id_alter_obra_fecha_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='fecha_final',
            field=models.DateField(default=datetime.datetime(2024, 12, 5, 4, 26, 23, 687549, tzinfo=datetime.timezone.utc), verbose_name='Fecha final'),
        ),
    ]
