# Generated by Django 4.2.13 on 2024-06-08 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0009_alter_obra_fecha_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='fecha_final',
            field=models.DateField(default=datetime.datetime(2024, 12, 5, 4, 26, 47, 710298, tzinfo=datetime.timezone.utc), verbose_name='Fecha final'),
        ),
    ]
