# Generated by Django 4.2.13 on 2024-06-08 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0010_alter_obra_fecha_final'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='id_capataz',
            new_name='id_capataces',
        ),
        migrations.RenameField(
            model_name='obrapersonal',
            old_name='id_usuarios',
            new_name='personal',
        ),
        migrations.AlterField(
            model_name='obra',
            name='fecha_final',
            field=models.DateField(default=datetime.datetime(2024, 12, 5, 4, 38, 51, 505185, tzinfo=datetime.timezone.utc), verbose_name='Fecha final'),
        ),
    ]
