# Generated by Django 4.2.13 on 2024-06-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0006_alter_obra_fecha_final'),
        ('construction_management', '0011_rename_id_capataz_obra_id_capataces_and_more'),
    ]

    operations = [
    ]
