# Generated by Django 5.0.6 on 2024-06-10 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0007_alter_obra_fecha_final'),
        ('construction_management', '0011_rename_id_capataz_obra_id_capataces_and_more'),
    ]

    operations = [
    ]
