# Generated by Django 4.2.13 on 2024-06-09 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0012_merge_20240609_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='img_obra',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fecha_final',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 21, 8, 15, 856115, tzinfo=datetime.timezone.utc), verbose_name='Fecha final'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='ubicacion',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
