# Generated by Django 4.2.13 on 2024-06-10 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0014_alter_obra_fecha_final_alter_obra_img_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='fecha_final',
            field=models.DateField(default=datetime.datetime(2024, 12, 7, 4, 22, 42, 617101, tzinfo=datetime.timezone.utc), verbose_name='Fecha final'),
        ),
    ]
