# Generated by Django 4.2.13 on 2024-06-10 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0017_alter_obra_fecha_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='fecha_final',
            field=models.DateField(default=datetime.datetime(2024, 12, 7, 6, 22, 55, 668255, tzinfo=datetime.timezone.utc), verbose_name='Fecha final'),
        ),
    ]
