# Generated by Django 5.0.6 on 2024-06-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0012_merge_20240610_1559'),
        ('construction_management', '0018_alter_obra_fecha_final'),
    ]

    operations = [
    ]
