# Generated by Django 5.0.6 on 2024-06-11 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0019_merge_20240611_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='fecha_final',
            field=models.DateField(default=datetime.datetime(2024, 12, 8, 8, 17, 25, 107909, tzinfo=datetime.timezone.utc), verbose_name='Fecha final'),
        ),
    ]
