# Generated by Django 4.2.13 on 2024-06-14 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0019_alter_obra_fecha_final'),
        ('construction_management', '0020_alter_obra_fecha_final'),
    ]

    operations = [
    ]
