# Generated by Django 4.2.13 on 2024-06-14 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0021_merge_20240614_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='fecha_final',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 1, 42, 21, 849537, tzinfo=datetime.timezone.utc), verbose_name='Fecha final'),
        ),
    ]
