# Generated by Django 4.2.13 on 2024-06-14 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0028_alter_obra_fecha_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='fecha_final',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 7, 4, 21, 470514, tzinfo=datetime.timezone.utc), verbose_name='Fecha final'),
        ),
    ]
