# Generated by Django 5.0.6 on 2024-06-14 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0032_alter_obra_fecha_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='fecha_final',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 17, 15, 7, 270253, tzinfo=datetime.timezone.utc), verbose_name='Fecha final'),
        ),
    ]
