# Generated by Django 4.2.13 on 2024-06-14 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_tareas', '0017_alter_tarea_fecha_estimada_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='')),
                ('img_avance', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('georeferencia', models.JSONField(blank=True, null=True)),
                ('tarea_porcentaje', models.IntegerField(default=0)),
                ('revision', models.BooleanField(default=False)),
                ('necesidades', models.CharField(choices=[('materiales', 'Materiales'), ('asignar más personal', 'Asignar más personal'), ('cambio condiciones climáticas', 'Cambio condiciones climáticas')], default='materiales', max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tareas.tarea')),
            ],
        ),
    ]
