# Generated by Django 4.2.13 on 2024-06-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advancements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='')),
                ('img_avance', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('georeferencia', models.JSONField(blank=True, null=True)),
                ('tarea_porcentaje', models.IntegerField(default=0)),
                ('revision', models.BooleanField(default=False)),
                ('necesidades', models.CharField(choices=[('materiales', 'Materiales'), ('asignar más personal', 'Asignar más personal'), ('cambio condiciones climáticas', 'Cambio condiciones climáticas')], default='materiales', max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
