# Generated by Django 5.0.6 on 2024-06-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avances', '0002_advancements_id_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancements',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
